### ISSUE TITLE
[Tool] The following KPIs should be added to the output report

### ISSUE THREAD

**Issue by FredericHirschmueller** [rl-institut/open_plan#131]
KPIs:

- internal energy consumption [kWh]
- self-sufficiency [%]
- charge level of the storage [kWh]
- source of energy supply of the battery and the consumer (grid supply, internal supply or both)

**Comment by Bachibouzouk** [comment]
internal energy consumption should be taken care of by [On-site Energy Fraction](https://multi-vector-simulator.readthedocs.io/en/latest/model/simulation_outputs.html#onsite-energy-fraction-oef) in MVS. And self-sufficiency by the [Degree of Autonomy](https://multi-vector-simulator.readthedocs.io/en/latest/model/simulation_outputs.html#degree-of-autonomy-da)

**Comment by Bachibouzouk** [comment]
charge level can be obtained via "energyStorage" --> <name of your storage asset> --> "storage capacity" --> "flow" --> "value" in the results json. (you need to devide it by the "energyStorage" --> <name of your storage asset> --> "storage capacity" --> "installedCap" --> "value" to get SOC between 0 and 1. It is already calculated for you and available in the `timeseries_all_busses.xlsx` file
