### ISSUE TITLE
[Tool] Show graphs and values of a timeseries when uploading it to a component

### ISSUE THREAD

**Issue by FredericHirschmueller** [rl-institut/open_plan#147]
It would be nice if one could see a graph and a table of the values of the timeries that has to be uploaded for specific components.

The graphs could be shown right below the input parameter where one has the option to upload a timeseries. An example is shown in the screenshot below.

Additionaly it would be nice if the graph would be interactive, like the graphs that are shown as a result of the simulation.

![Unbenannt](https://user-images.githubusercontent.com/70587431/141337081-a6c9e87e-04f1-4e9c-a934-b9f2ccbfb5f7.PNG)

**Comment by Bachibouzouk** [comment]
solved in https://github.com/open-plan-tool/gui/commit/a9a65cc0f6bf457c35212807aab138e4a52768eb
