### ISSUE TITLE
Descriptions of views are missing

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/open_plan#18]
- start new scenario
- load old scenario
- scenario comparison
- current scenario

**Comment by TheOneAndra** [comment]
@Bachibouzouk and @mahendrark: @TheOneAndra is working on scenario comparison

**Comment by mahendrark** [comment]
For the scenarios, I am in discussion with @TheOneAndra before writing the description of the view components. 
We are going to do a little brains storming like @Bachibouzouk and myself did on how to come up with a secnario selection and comparison interface that is in harmony with all of the proposals submitted at and after Q3.

**Comment by mahendrark** [comment]
After discussion with @TheOneAndra, we agreed that Scenarios need to removed from the menu bar and moved to the progression bar. It is now to be situated before the inputs. 

The project inputs including location coordinates and name of the project should be same for every scenario. 
A project can have one scenario or can be a collection of scenarios. 

Switching between scenarios and changing scenario settings, etc., can be done using the scenario step in the progression bar.

**Comment by Bachibouzouk** [comment]
You should define what you exactly mean by a *scenario* to start with @TheOneAndra, @mahendrark, then we can discuss where to place it

**Comment by Bachibouzouk** [comment]
For me a scenario is defined by one energy system (defined itself by information about its components + busses + connections between them) and input parameters. You could not compare scenario A with scenario B if they don't have the same energy system

**Comment by Bachibouzouk** [comment]
The progression bar helps me to build a scenario, the scenario is one of the output of going through the progression bar. You need to handle different scenarios to compare them, and you do so without a progression bar, therefore the scenario cannot exist only within a progression bar

**Comment by mahendrark** [comment]
_load scenario_ and _create scenario_ would be view-components of the scenarios view, rather than views by themselves
