### ISSUE TITLE
Definition of a Scenario is missing

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#25]
We need to agree on a definition of a _Scenario_ in the context of an energy system. 

As a starting point, I am copy-pasting verbatim, the definition proposed by @Bachibouzouk in issue #22: 

> For me a scenario is defined by one energy system (defined itself by information about its components + busses + connections between them) and input parameters. You could not compare scenario A with scenario B if they don't have the same energy system. 

> The progression bar helps me to build a scenario, the scenario is one of the output of going through the progression bar. You need to handle different scenarios to compare them, and you do so without a progression bar, therefore the scenario cannot exist only within a progression bar

**Comment by mahendrark** [comment]
I agree with the idea that a _Scenario_ is one specific output of an energy system. 

As I see it, a _Project_ could have only one scenario or be a collection of related scenarios. They be should be comparable even if they are not exactly similar (otherwise whats the point of comparison?). For e.g.: Scenario 1 may only include the electricity system, but scenario might include electricity+heat system. Both the scenarios are part of one project and should be reasonably comparable for KPIs of performance, economics, etc.

**Comment by Bachibouzouk** [comment]
Actually, one could still consider that electricity or heat + electricity is the same energy system, just with input parameter that the demand on  heat is always equal to 0, and production equal to 0 (in a sense the network graph for the two electrical system have to be the same, no?

If one scenario implements H2, and the other not, then how to you compare H2 production or H2 costs between the two scenarios? This comparison does not really make sense -> the cost of electricity or heat could still be compared between these two scenarios, to see how the H2 influences them

**Comment by mahendrark** [comment]
@TheOneAndra proposed that we move the "Scenarios" menu from the Menu bar to Progression bar, and I agreed with that. 

The rationale behind that is as follows:
Since each Project may have multiple Scenarios which share some common project data such as location, name of the project of which they are part, etc. 

So after launching the tool, the user starts the simulation process by first completing the Project Setup step. Then if we introduce Scenarios, user can define the scenarios there itself and then proceed ahead with the further setup of the energy system in each scenario. It is more fluid than going to the menu bar to work with the scenarios.

**Comment by mahendrark** [comment]
> If one scenario implements H2, and the other not, then how to you compare H2 production or H2 costs between the two scenarios? This comparison does not really make sense -> the cost of electricity or heat could still be compared between these two scenarios, to see how the H2 influences them

Of course the capital and O&M would surely be higher in the case where we include the heat system. But maybe the total renewable share rises and per capita Carbon emissions of the Geographical area under consideration decreases because both electricity and heating systems are considered in the modelling with RER. 

Yes, if heating is ignored in Scenario 1, then costs, demand, production, etc would be 0 (as default).

**Comment by mahendrark** [comment]
According to @TheOneAndra, Scenario Comparison after the simulations of each scenario can be included as part of the results, or a separate step in the Progression bar itself.

**Comment by mahendrark** [comment]
Perhaps we can also ask Caroline and Sarah for their inputs now (or after we present our own agreed-definition)? 
@Bachibouzouk can we tag them here?

**Comment by Bachibouzouk** [comment]
@srhbrnds and @c-moeller

**Comment by Bachibouzouk** [comment]
> So after launching the tool, the user starts the simulation process by first completing the Project Setup step. Then if we introduce Scenarios

What about directly loading older scenarios? You still did not provide a valid counter argument to 
> You need to handle different scenarios to compare them, and you do so without a progression bar, therefore the scenario cannot exist only within a progression bar

**Comment by TheOneAndra** [comment]
I think we are going at this the wrong way. We could first dertermine what we want to compare in this "comparison" part. and that will tell us what we include in a scenario and what not. then it will be clearer where to put it

**Comment by Bachibouzouk** [comment]
> I think we are going at this the wrong way. We could first dertermine what we want to compare in this "comparison" part. and that will tell us what we include in a scenario and what not. then it will be clearer where to put it

@TheOneAndra, If you think the current way is wrong and you propose something else, you should lay the first stone in this new direction so that we can iterate :)

**Comment by mahendrark** [comment]
What can be compared across scenarios? What could be the differences in setting up different scenarios? 

1. Sector coupling: One scenario might have E+H+T, other only E+T sectors
2. Technologies: One scenario might only employ Solar PV, but not Solar thermal 
3. Different costs (imposing higher costs on Coal in one scenario for e.g.)
4. Different emission restrictions in different scenarios
5. Degree of autarky 
6. Renewable share in the system 
7. Availability of land area: One scenario might allow for rooftop PV systems, but another not (here, we have to first settle the GIS issue #26 I think) 

Please add more points, if you do have any. 
Thanks to @TheOneAndra for some of the above points.

**Comment by srhbrnds** [comment]
Hey there, 
here is our definition of energy scenario as we use it in the open_MODEX project: https://next.rl-institut.de/s/7TQyBodtKbW2XSK

For definitions of _model_ or _framework_, we go with the glossary in the OpenMod-Wiki: https://wiki.openmod-initiative.org/wiki/Category:Glossary

**Comment by mahendrark** [comment]
Scenario and project definitions are missing in the description of the abstract view-components scenario and project.

**Comment by TheOneAndra** [comment]
I will draft something based on issue #58
