### ISSUE TITLE
How to handle GIS data in a project is not defined

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#26]
I am not sure how important this is, but it came in the discussion yesterday between me and @TheOneAndra. 

When modelling an energy system, the area under consideration (like a neighborhood or industrial suburb, etc) should be defined. In MVS for e.g., I recall that the user only has to provide the location co-ordinates and supply the demand time series and the tool will output the capacities of the different technologies that ought to be installed to meet the demand. 

In case of PVCompare, since net-zero energy neighborhoods are considered, the approach followed is that the user has to give the number of inhabitants per neighborhood (or building) and based on that the demand is calculated using demandlib and then the tool outputs the optimized capacities of PV to be installed. 

So in our case, since its energy cells, should we require the user to define geographical coordinates of the area under consideration, or just one location (center of the area) and we assume a certain radius?

**Comment by mahendrark** [comment]
Maybe in one scenario, we do not allow rooftop PV and in another we do. In that case, the requirement will vary. In this situation, I forsee that the user has to specify how much land area is available for installing RE infrastructure.

**Comment by catcad** [comment]
From my perspective, the minimum we would need is one point location (lat/long) data, e.g. the centerpoint of the energy cell in order to draw resource data (e.g. solar irradiation, wind speed time series) for the simulation for that specific case.
More than that would be optional from my perspective by now...e.g available space for PV, area etw.
@oemof expert @c-moeller : Do you usually have more than one spatial coordinate as an input to run an oemof simulation?

**Comment by mahendrark** [comment]
> From my perspective, the minimum we would need is one point location (lat/long) data, e.g. the centerpoint of the energy cell in order to draw resource data (e.g. solar irradiation, wind speed time series) for the simulation for that specific case.
> More than that would be optional from my perspective by now...e.g available space for PV, area etw.

I agree with your points. 

To add to this discussion, I have a question regarding scenarios. Can two scenarios of the same project have energy system simulations with different locations? I think this should be under the scenario definition discussion, but nevertheless since we are talking about spatial matters here, I am raising it here.
