### ISSUE TITLE
Description of views for each steps in Progression Bar

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#37]
Each step in the simulation process is an option (or menu) in the progression bar. When clicked or navigated between, opens a new view of the tool with the options required for that corresponding  step in the simulation. 

I would like to start at the first option, "Project Setup" and describe each view with all the view-components in it. 

Do you agree with that? @Bachibouzouk

**Comment by Bachibouzouk** [comment]
> Each step in the simulatin process is an option (or menu) in the progression bar

each step is just a step :) Do not introduce two new terms (option and menu) now that "step" was clearly defined in RTD in the view component's description. 

I would actually wait for approval of the steps by other people before we dive in further. What you could do is to describe a bit more each currently choosen steps (i.e. what are the differences between "Project setup", "Inputs" and "System inputs")
