### ISSUE TITLE
Two view components could be merged into one

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/open_plan#41]
It appears to me that project_parameters and scenario_parameters view-component could be described by a single more generic view component. Both of them define input parameters. I therefore think that the view-component could describe what are the features we want to have for generic input parameters such as:

- Each parameter can have explanatory text with a ? icon which describes briefly the parameter and provide a link to documentation for in depth explanation (a link to this icon file would be an attribute of the view-component "input-parameters")

- Each parameter has a type (scalar, str, timeseries, matrix, array) and we could describe how the user can input things that are not scalar or str (e.g. a "..." icon next to the parameter name instead of a text input for timeseries)

- If the user changes a parameter's value, then something should happen to signify the user that what is displayed on the screen is not yet what is simulated (a parameter can been seen as changed on the GUI, however the results can still be the previous one, we need to prevent this type of confusion to happen)

On of the attribute would be "List of parameters", then the scenario_parameters view-component could simply be expressed as this "input parameters" view-component with a list of parameters.

For this we probably need an abstract definition of what a "parameter" is and which attributes it has as well (right now I see type, unit, value)

**Comment by Bachibouzouk** [comment]
After our discussion we decided to describe "input parameter field" as an abstract component and to keep the `project_parameters` and `scenario_parameters` view-component. We need to describe each parameter in another chapter of the RTD structure and simply list the references to these parameters in the view-compnent section

**Comment by mahendrark** [comment]
Based on this thread, I will create an abstract view-component for input_parameter_field. 

I would also like this to be generic enough text input field that can be used elsewhere, such as in... constraints, etc. views.

**Comment by Bachibouzouk** [comment]
If they are to be generic, they should not be "text fields" ;)

**Comment by mahendrark** [comment]
> If they are to be generic, they should not be "text fields" ;)

But even if it is any other input, lets say, time-series CSV file.. within the input field it must be a file path (string) right? Of course, in that case, the field itself should be accompanied by a Upload button of some sort to load the time-series. What would you say?

**Comment by Bachibouzouk** [comment]
I would consider every type of inputs (see first thread) and just call the attribute "input field", then say it is "input text" for scalar, and something else for other types
