### ISSUE TITLE
[Discussion] Progression bar 

### ISSUE THREAD

**Issue by TheOneAndra** [rl-institut/open_plan#48]
What is showing in the simulation part of the flowchart?
Is it: click on simulation, *simulation is happening* then when it is finished, click on results ?

If this is the case, we could jump from constraint to results: When clicking on results a pop-up loading bar shows the simulation is happening (a pop-up log could also work here) and when simulation is done, the user is automatically put on the result window.

**Comment by Bachibouzouk** [comment]
NB: Flow chart was renamed "Progression Bar"

**Comment by TheOneAndra** [comment]
My bad, it is like that in the RDT, I got confused by "open_plan/docs/_build/html/_images/flow_chart.png"

Nevertheless, thoughts on the simulation tab @Bachibouzouk ?

**Comment by mahendrark** [comment]
@TheOneAndra 

I imagined that the user can see some log messages and warnings, and of course the progress bar

But we can have all that in a pop-up window as well

**Comment by Bachibouzouk** [comment]
When starting a simulation should the user be able to do something else while waiting for the results?

The action "start simulation in the backend with currently defined parameters" can be executed in many different ways:
1. as you mentioned by clicking on link to results view from constraints view
2. By clicking to run simulation from constraints view
3. In the menu bar selecting option "start simulation with current parameters" (useful if you go back to edit one or two input parameters)
4. With an hotkey (ctrl + SHIFT + 'r')
5. by clicking on link to results view in the progression bar, as long as the necessary steps have been fulfilled and that no input data is missing

I think it was wished that the user could click "next" in the progression bar, fill nothing and it should nevertheless simulate a default example simulation, so in that case all steps of the progression bar would always be reachable. I think we can ensure that the user is not moving to any other view if some of its input is faulty (or at least prevent the run of the simulation in that case).

In the use case where the user is comparing scenarios while launching new scenarios, this would be annoying to be directed to the result page of the latest simulation. I could rather see a popup with "Simulation is over" and "Go to result now"/"Look at it later" option.

**Comment by TheOneAndra** [comment]
> I think it was wished that the user could click "next" in the progression bar, fill nothing and it should nevertheless simulate a default example simulation, so in that case all steps of the progression bar would always be reachable.

Interesting comment, we didn't discuss about that part yet. Indeed it is a wish that there are default values for each input fields in the tool. Nevertheless when starting the tool, I think having an energy system already built is confusing for the user and annoying (as the user will have to delete component to adapt to their desired system). 

So, an option is that there are default values for each input fields but the energy system is not built yet. It means the user has to go through all the steps of the progression bar and therefore chose at least a load and a power source but all required inputs for those can have a default value. 

This way clicking direclty on _**Results**_ from **_Constraint_** (considering it is the last view of the progression bar) would launch the simulation. 

If the user wants to go directly to results (for whatever reason) there would be 2 options: 
1. The user can import a scenario file that has already been simulated (in that case all steps of the progression bar are clickable)
2. The user can chose a sample energy system from the menu (which is basically a scenario created by the dev team and that comes with the tool to give an example). 

N.B.: With this layout, the scenario comparison could be done by clicking a **compare with another scenario** button in the **_Result_** tab

**Comment by Bachibouzouk** [comment]
> I think having an energy system already built is confusing for the user and annoying (as the user will have to delete component to adapt to their desired system).

That is a good point. To address it we can also: 
1a. have values as placehoder (you don't need to delete the value in the field, you can simply write over it)
1b. have default values and remove all of them if the user edit at least one field
2. have a button "Delete all parameter values" on each view (deleting only the parameters accessible by this view


>  there are default values for each input fields but the energy system is not built yet
What about input fields for energy system (i.e. its components)? 

I think the two options you propose make sense, if the user click on *Result* directly after landing (provided we all agree on having the progression bar visible from start), a warning message will tell them that they need to either import their own scenario or load an example scenario.



> N.B.: With this layout, the scenario comparison could be done by clicking a **compare with another scenario** button in the **_Result_** tab

*One* of the ways to land on the **compare with another scenario** view. If it is a view, we can access it by different ways, I am a proponent of the ability to use the tool to compare previous simulations results without having to build/run any scenarios.

**Comment by TheOneAndra** [comment]
> That is a good point. To address it we can also:
> 1a. have values as placehoder (you don't need to delete the value in the field, you can simply write over it)
> 1b. have default values and remove all of them if the user edit at least one field
> 2. have a button "Delete all parameter values" on each view (deleting only the parameters accessible by this view

I imagined it as 1a. as it something common and intuitive.

> _One_ of the ways to land on the **compare with another scenario** view. If it is a view, we can access it by different ways, I am a proponent of the ability to use the tool to compare previous simulations results without having to build/run any scenarios.

I agree with that idea. What i mean is: 
To compare scenrios you need already simuted systems. Therefore launching the tool, import a scenario, clicking directly to result (clickable if imported scenario was already simulated and no inputs have been changed) and then compare with another (simulated) scenario if desired.
This method also leaves the possibility for the user to double check the energy system and input values before comparing. The user has also the possibility to change a value and rerun the simulation before comparing if needed.

**Comment by mahendrark** [comment]
In any case, we do not need the "Simulation" view in the Progression Bar, as per this discussion. I am omitting it from the Progression Bar for the moment. 

Now, "Constraints" view should have a button "Start Simulation" and clicking this should launch a pop-up window showing the progress of the simulation. One the simulation is complete, user can close the pop-up and return to the Constraints view and proceed to results. 

So then, there are 6 steps in the Progression Bar. 

Do you agree?

**Comment by TheOneAndra** [comment]
>Now, "Constraints" view should have a button "Start Simulation" 

No I disagree. The whole point of getting rid if the _Simulation_ tab is to facilitate the process. Therefore, clicking on _Results_ would launch the simulation. Once the simulation is finished, the _Results_ tab is shown. 

This way, if the user loads a scenario which was already simulated, the user can directly click on _Results_  and the simulation results are there. But if the user changes one value somewhere before, and then clicks on _Results_, the simulation pop-up appears and once the simulation is finished, the _Results_ tab is shown.

**Comment by mahendrark** [comment]
> The whole point of getting rid if the _Simulation_ tab is to facilitate the process. Therefore, clicking on _Results_ would launch the simulation. Once the simulation is finished, the _Results_ tab is shown.

Normally, I would go to Results only after I am done with the simulation process. So it would be logical to have the simulation finished beforehand. 

If I have a file with results of a simulation done previously. I can still load it and skip to Results to visualize them.

**Comment by TheOneAndra** [comment]
> Normally, I would go to Results only after I am done with the simulation process. So it would be logical to have the simulation finished beforehand.

Here is another way to see it: What do you do after you launch the simulation? You go to _Result_ because that is the goal of the simulation. So why having to bother with a specific command for the simulation if anyway what you will do after is looking at the _Result_ ? Might as well click on _Result_ directly.

> If I have a file with results of a simulation done previously. I can still load it and skip to Results to visualize them.

As I said here:
>This way, if the user loads a scenario which was already simulated, the user can directly click on Results and the simulation results are there. But if the user changes one value somewhere before, and then clicks on Results, the simulation pop-up appears and once the simulation is finished, the Results tab is shown.

Is that not well explained? I can try to rephrase it :)

**Comment by Bachibouzouk** [comment]
> No I disagree. The whole point of getting rid if the _Simulation_ tab is to facilitate the process. Therefore, clicking on _Results_ would launch the simulation. Once the simulation is finished, the _Results_ tab is shown.

I agree that we get rid of the _Simulation_ tab, but I also agree that the button _Next_ in the _Contraints_ view could be labeled "Start simulation" as this is the last step before _Results_ now.

You can include this things which happen "meta" under the links in the mockup GUI_draft (to explain what we think should happend when clicking on the button, as right now we don't want to implement popups and such)

**Comment by TheOneAndra** [comment]
> I agree that we get rid of the _Simulation_ tab, but I also agree that the button _Next_ in the _Contraints_ view could be labeled "Start simulation" as this is the last step before _Results_ now.

Ok I see now the issue. For me jumping from tab to tab is more intuitive by clicking on the next tab in the progression bar than clicking a "next" or "previous" button. As there are so many stuff on screen already, having the progression bar on top and being able to click on the tab the user wants to access allows to quickly move in the tool instead of clicking "previous" or "next" until reaching the window the user wants to see. 

By clicking on the progression bar, the user can directly jump to result:
1. Once a scenario has been imported
2. Once at least a load and a power source have been put in the energy system.

No need to click "next" seven times to access _Result_ or simulate.
If user load a scenario and click on _Results_ and notice that one input should be changed: User can directly click on the tab they want to access, modify the input, click again on _Result_ and the simulation starts. Then _Result_ tab is shown. 

> I agree that we get rid of the _Simulation_ tab, but I also agree that the button _Next_ in the _Contraints_ view could be labeled "Start simulation" as this is the last step before _Results_ now.

Implies for the example above that the user would have to modify the input, then **remember** to click back on the last tab to launch a simulation again

**Comment by Bachibouzouk** [comment]
> Ok I see now the issue. For me jumping from tab to tab is more intuitive by clicking on the next tab in the progression bar than clicking a "next" or "previous" button

That is why we'll allow both ;). It was always clear to me that you can have many ways to get to see a given view (at least one, but no upper bound)

**Comment by Bachibouzouk** [comment]
The next/previous buttons should be available in each step view to get to the next/previous step, but one can _also_ browse through the step views via the progression bar
