### ISSUE TITLE
Description of view components is missing 

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/open_plan#5]
@mahendrark :
- [x] view_components/flow_chart.rst
- [x] view_components/menu_bar.rst
- [x] view_components/welcome.rst

@Bachibouzouk :
- [x] view_components/energy_system_schema.rst
- [x] view_components/energy_system_component.rst
- [x] view_components/energy_system_sector_selector.rst

@TheOneAndra :
- [x]  view_components/project_parameters.rst
- [x] view_components/view_template.rst

**Comment by Bachibouzouk** [comment]
@mahendrark, @TheOneAndra We need to agree on how we list attributes, in the welcome.rst file `#. ` was used, but in flow_chart.rst `*` was used.

The first one creates a numbered list, the second one bullet points. I think I am more in favor of bullet points, what do you think?

**Comment by mahendrark** [comment]
> The first one creates a numbered list

Changed it to bullet points now

**Comment by TheOneAndra** [comment]
> 
> 
> @mahendrark, @TheOneAndra We need to agree on how we list attributes, in the welcome.rst file `#. ` was used, but in flow_chart.rst `*` was used.
> 
> The first one creates a numbered list, the second one bullet points. I think I am more in favor of bullet points, what do you think?

How about:

```
**Attribute 1**
* text
* text


**Attribute 2**
* text
```

Which is rendered

**Attribute 1**
* text
* text


**Attribute 2**
* text

**Comment by Bachibouzouk** [comment]
Highlight the attributes

- No listing of attributes (with bullet or numbers)
- Have indent after the attribute name and write description
- Set them bold with ** ** 
-> find a way to highlight all of them (when no text is under the attribute)
- if applicable 
```
property:
   * prop1
   * prop2
```
Otherwise a one liner or a list of linebreak separated indented paragraphs

Use comment on the template to carry these styling points

**Comment by Bachibouzouk** [comment]
@TheOneAndra : modify the template

**Comment by TheOneAndra** [comment]
To represent a button part of the interactive user interface we can use 
```
:guilabel:`&<ButtonName>`
```
@Bachibouzouk

**Comment by Bachibouzouk** [comment]
> To represent a button part of the interactive user interface we can use
> 

Nice, but where would you use this in the RTD ?

**Comment by TheOneAndra** [comment]
> 
> 
> > To represent a button part of the interactive user interface we can use
> 
> Nice, but where would you use this in the RTD ?

For example in Energy System network
```
1. button `add_es_bus`
2. button `remove_es_bus`
```
Could be replaced by: 
```
1. :guilabel:`&add_es_bus`
2. :guilabel:`&remove_es_bus`
```
(Does not render correctly here, it looks like:
![grafik](https://user-images.githubusercontent.com/66671861/96454182-cac11300-121b-11eb-8591-a40a81561d07.png)

**Comment by Bachibouzouk** [comment]
It is not intuitive that this refers to a button in an interface to me, I prefer not dropping the explicit word "button"

**Comment by TheOneAndra** [comment]
We don't have to drop the word "button", we can combine like so:
```
**button** :guilabel:`&add_es_bus`
```
which renders:
![grafik](https://user-images.githubusercontent.com/66671861/96609394-c586c580-12fa-11eb-9b26-83733ce818d0.png)

**Comment by Bachibouzouk** [comment]
in that case I agree :)
