### ISSUE TITLE
Should there be a view-component for reading sections of RTD from within the tool ?

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#50]
While working on #49, I felt that we need to create a view-component for visualizing the documentation from within the tool. 
For instance, when the user inputs the values for input fields, they click an icon next to the field label and a pop-up opens with the relevant sections of the documentation.

**Comment by Bachibouzouk** [comment]
Yes I agree. This was also described in the protocol of the Q3 meeting for the Anna-Ekatherina's design, did you read the protocol?

**Comment by mahendrark** [comment]
Cool, I have read it and I vaguely remember something like this. Anyway, I will work on this after the current PRs are closed.
