### ISSUE TITLE
View-component load_input_dataseries is not described yet

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/open_plan#55]
This is a view-component where the user can choose to upload arrays, .xls, .csv files as value for a parameter, this is linked to the view-component [input_parameter_field](https://open-plan.readthedocs.io/en/latest/tool_interface.html#input-parameter-field)

File exists

**Comment by mahendrark** [comment]
this is for inputs that are a series of data 

user should be able to quickly visualize the data in a plot

**Comment by mahendrark** [comment]
![Scan_RLI_20110313460](https://user-images.githubusercontent.com/13640220/97987150-19a1a780-1ddb-11eb-80d4-014c4e956990.jpg)

I propose this structure for this view-component
