### ISSUE TITLE
Project VS Scenario

### ISSUE THREAD

**Issue by TheOneAndra** [rl-institut/open_plan#58]
Before working deeper on **project** and **scenario** definitions, it would be good to define what _inputs_ are part of a project and what _inputs_ are part of a scenario. 
This would help to solve #56 #55 #53 #54 and #25

**Comment by TheOneAndra** [comment]
**Project** is a file with a name (most probably in a non-universal format) that regroups the state of the tool when the **project** was saved. Thus a project can be used to save a specific scenario comparison, one or more energy systems, ...

**Scenario** is a file with a name (most probably in a range of format to be universal) that has the information of an energy system and possibly the result of a simulation.

**Comment by TheOneAndra** [comment]
I see this differnce mostly in: 
A **project** holding the GIS and the loads information (and therefore the concerned energy sectors).
A **scenario** having all other inputs such as power source, constraints, etc.

Therefore a **scenario comparison** allows to compare different energy systems (or similar ones with different constraints) with regard to the same load.

**Comment by Bachibouzouk** [comment]
I agree with the conceptual distinction beeing made between project and scenario. I think this cannot be a file, rather a data structure or a folder (especially for timeseries for loads or weatherdata).

A *project* can contain many *scenarios*, a *scenario* is part of one *project*.

To work with open_plan tool we can separate things like that (i.e. *project* holds the information about the load), however, we need to think data exchange with other tools and I think data such as load should also be included in the datapackage of a *scenario* to be more sharable.

In that sense, I would include a field "project_data" in the *scenario* data package, which contains the *project* input parameters. One information I see that a project data package would have, could be the path to the scenarios datapackages which are considered within the project, and some choices for comparison plots. Even if most of the *project* input parameters will also be available in the *scenario* data package, it make sense to distinguish the two by asking the question: "can this parameter be the same across all scenario or not?", if it can be the same --> project data, if it changes for certain scenarios --> scenario data

**Comment by mahendrark** [comment]
Maybe we completely do away with the idea of project parameters and include all of them just in the scenario parameters? In that case the project just being a container of scenario files seems good.

**Comment by Bachibouzouk** [comment]
I think it is still nice to categorize input parameters, so I would still caracterize project parameters vs scenario parameters

**Comment by TheOneAndra** [comment]
To help us draw the separation between **project** and **scenario** we could take another software as example to help us: 
In QGIS or ArcGIS I believe there is a similar distinction. A project is a collection of maps, scenes, layouts, data, etc. A single map (scenario), on the contrary, is the render of all the ticked layers.

This could mean for open_plan:
**A project** is a collection of 1 to n scenarios with all the values and a local copy under a common folder of all files put in the tool.
**A scenario** is one energy system optimization with all values and link to the files put in the tool. 

Therefore, in order to do a scenario comparison, one would have to create a **project** which would build a folder in which are imported all **scenarios** and their data needed for that comparison.

**Comment by Bachibouzouk** [comment]
I agree with that disctinction between project and scenario :)
