### ISSUE TITLE
RTD full screen

### ISSUE THREAD

**Issue by TheOneAndra** [rl-institut/open_plan#60]
Is it possible to set the RTD in a way that it takes the full screen and not just half of it? 

An example of full screen here:
https://temoacloud.com/temoaproject/Documentation.html

An example of half screen (like open_plan now) here:
https://multi-vector-simulator.readthedocs.io/en/latest/Overview.html

**Comment by Bachibouzouk** [comment]
As temoa is open source, you can go look in their documentation's confirguration to see where they could have set that parameter. You can probably also google it (I can do it but there is learning potential for you there :))

**Comment by Bachibouzouk** [comment]
It is worth trying I think, I am not sure who looks at the docs on their smartphones

**Comment by TheOneAndra** [comment]
> As temoa is open source, you can go look in their documentation's confirguration to see where they could have set that parameter. You can probably also google it (I can do it but there is learning potential for you there :))

I couldn't find the answer to my question. 
I also checked conf.py from Temoa/docs but it seems they use the same html_theme = "sphinx_rtd_theme" as us.

**Comment by Bachibouzouk** [comment]
https://stackoverflow.com/questions/23211695/modifying-content-width-of-the-sphinx-theme-read-the-docs
