### ISSUE TITLE
The definition of certain input and output parameters is not clear

### ISSUE THREAD

**Issue by FredericHirschmueller** [rl-institut/open_plan#64]
minimal peak power capacity = installed power

Available production technologies = Available generation and storage technologies
Tool has a list of technologies on the market, user inputs list of what is available. Tool would cross some technologies off the list based on requirements.

required size of electrolysers and batteries = required size of storages
Required size of electrolysers, batteries, thermal storages, etc.

**Comment by TheOneAndra** [comment]
I agree except for 1 detail:

Available production technologies = Available generation technologies

Since the storage is included in the next line:
Required size of electrolysers, batteries, thermal storages, etc.

**Comment by Bachibouzouk** [comment]
> Since the storage is included in the next line:

It seems to me that the size of the storage is not the same as "which storage technology is available"

> minimal peak power capacity = installed power

I thought that the installed power can be larger than the minimal peak power capacity. In my understanding, the minimal power capacity is what capacity is minimally needed to satisfy the given power demand.

**Comment by TheOneAndra** [comment]
@FredericHirschmueller , this issue was closed automatically because PR #59  was merged.

Refer to PR #100  to see the changes
