### ISSUE TITLE
View-component describing the input/output file selection window missing

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#66]
The view-component that describes the pop-up window that appears when the user wants to load a file from disk or save data to a file on disk or write to a new file, is missing.

**Comment by mahendrark** [comment]
![Scan_RLI_20110316050](https://user-images.githubusercontent.com/13640220/98003245-ca657200-1dee-11eb-84ee-ce587e21782c.jpg)

I modeled this after read/write file pop-up windows in Xubuntu (open source)

**Comment by mahendrark** [comment]
@Bachibouzouk 

should I describe this view-component or just leave it as 'File Explorer'. Issues #53, #54 and #56 are linked to this view-component.

**Comment by TheOneAndra** [comment]
I would say to leave it as file explorer is enough. Maybe we can specifiy that in the defintions of a project and scenario. See PR #102

**Comment by mahendrark** [comment]
> 
> 
> I would say to leave it as file explorer is enough. Maybe we can specifiy that in the defintions of a project and scenario. See PR #102

@Bachibouzouk also suggested the same. So then, we can close this issue as there is agreement.
