### ISSUE TITLE
The Energy Cells Explained section is missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/open_plan#71]

**Comment by TheOneAndra** [comment]
_[intro on the german energy transition target?]_
The cellular approach was developed by the German Association for Electrical Engineering, Electronics and Information Technology, VDE. This concept proposes a new way to organize future energy system networks. It incorporates the idea that the production and consumption of energy are locally balanced forming a so-called energy cell. An energy cell is not geographically limited but it is a system composed of at least a generator, a converter, a storage unit, a grid connection, a load and a protection and control system. An energy cell can contain many forms of energy such as electricity, heat, gas and mobility thus embracing the concept of sector coupling. An energy cell can also be composed of only one form of energy. It is recognized that a cell should be planned at the smallest level possible but that it is scalable in a way that many energy cells can form a bigger cell. The taskforce has assess the potential for the cellular appraoch in Germany at a local, regional and supra regional zoom level.

**Comment by TheOneAndra** [comment]
"The cellular approach is a new organizational model for energy supply. In this interdisciplinary model, technical, economic, legal and political (and social) concerns are taken into account. The central component of this model is the energy cell. 
[...] 
An energy cell consists of the infrastructure for different forms of energy, in which the balancing of production and consumption is organized by an energy cell management in possible coordination with neighboring cells using all available forms of energy.
[...]
The energy cells are used to build the energy system. The structure is repeated on all network levels."


_VDE Verband der Elektrotechnik Elektronik Informationstechnik e.V.: Cellular Energy System - A Contribution to the Concretization of the Cellular Approach with Recommendations for Action, Frankfurt am Main, May 2019_

**Comment by Bachibouzouk** [comment]
Does the second message replace the first one as a proposition @TheOneAndra ?

**Comment by TheOneAndra** [comment]
These are just different propositions we can build on

**Comment by catcad** [comment]
I added an introductory paragraph and merged/adapted some of Andras parts:

The adoption of the German Renewable Energy Law „EEG 2021“ opens a unique opportunity to be leveraged by taking an energy cell perspective: The full transition to renewable energy sources and climate neutrality by 2050 requires a high level of citizens' acceptance, reachable by local participation opportunities such as framworks to enable tenants to benefit from roof-top PV installations and local authorities from wind power generation. These are just two examples how bottom-up approaches can contribute to a successful energy transition, ultimatively requiring a cellular approach:
"The cellular approach is a new organizational model for energy supply. In this interdisciplinary model, technical, economic, legal and political (and social) concerns are taken into account. The central component of this model is the energy cell.
[...]"
The cellular approach was developed by the German Association for Electrical Engineering, Electronics and Information Technology, VDE. This concept proposes a new way to organize future energy system networks. It incorporates the idea that the production and consumption of energy are locally balanced forming a so-called energy cell. An energy cell is not geographically limited but it is a system composed of at least a generator, a converter, a storage unit, a load and a protection and control system, connected via a distribution grid. An energy cell can contain many forms of energy such as electricity, heat, gas and mobility thus embracing the concept of sector coupling.

_https://www.bmwi.de/Redaktion/DE/Downloads/G/gesetzentwurf-aenderung-erneuerbare-energien-gesetzes-und-weiterer-energierechtlicher-vorschriften.pdf?__blob=publicationFile&v=4_

_VDE Verband der Elektrotechnik Elektronik Informationstechnik e.V.: Cellular Energy System - A Contribution to the Concretization of the Cellular Approach with Recommendations for Action, Frankfurt am Main, May 2019_

**Comment by TheOneAndra** [comment]
>"The cellular approach is a new organizational model for energy supply. In this interdisciplinary model, technical, economic, legal and political (and social) concerns are taken into account. The central component of this model is the energy cell.
[...]"
> _VDE Verband der Elektrotechnik Elektronik Informationstechnik e.V.: Cellular Energy System - A Contribution to the Concretization of the Cellular Approach with Recommendations for Action, Frankfurt am Main, May 2019_

It is worth mentionning here that the original document from where the citation comes from is in German. The citation and bib have been translated using DeepL.
Would you like the German version to double check?

**Comment by TheOneAndra** [comment]
**I put some small changes but I tried to keep at as close as possible from what you wrote:**

The adoption of the German Renewable Energy Law „EEG 2021“ opens a unique opportunity to be leveraged by looking at new energy system planning perspective. The full transition to renewable energy sources and climate neutrality by 2050 requires a high level of citizens' acceptance, reachable by local participation opportunities. Such frameworks can enable tenants to benefit from rooftop PV installations and local authorities to value wind power generation. These are two examples that show how bottom-up approaches can contribute to a successful energy transition, ultimatively requiring a cellular approach: "The cellular approach is a new organizational model for energy supply. In this interdisciplinary model, technical, economic, legal and political (and social) concerns are taken into account. The central component of this model is the energy cell." [1]

This model was developed by the German Association for Electrical Engineering, _VDE_. It proposes a new way to organize future energy system networks. The cellular approach incorporates the idea that the production and consumption of energy are locally balanced forming a so-called energy cell. An energy cell is not geographically limited but it is a system composed of at least a generator, a converter, a storage unit, a load, a protection and control system and a connection to the distribution grid. An energy cell can contain many forms of energy such as electricity, heat, gas and mobility thus embracing the concept of sector coupling.

https://www.bmwi.de/Redaktion/DE/Downloads/G/gesetzentwurf-aenderung-erneuerbare-energien-gesetzes-und-weiterer-energierechtlicher-vorschriften.pdf?__blob=publicationFile&v=4

[1] VDE Verband der Elektrotechnik Elektronik Informationstechnik e.V.: Cellular Energy System - A Contribution to the Concretization of the Cellular Approach with Recommendations for Action, Frankfurt am Main, May 2019

**Comment by catcad** [comment]
Thanks Andra!
Can we put it already in the code such that we can track changes? I acually would like to change a few things again but I think it does not make sense to change the section above again since then we do not see changes. 
Can someone please advise here where/how to put it in code structure from where Bryan can use it? @TheOneAndra @bmlancien

**Comment by TheOneAndra** [comment]
Exsting PR #83 seems to be adapted for that.
I just pushed it, see commit e8bc510

**Comment by bmlancien** [comment]
@catcad @TheOneAndra I'm changing the structure of the EC explained section because of the high amount of new text. It didn't fit the former design anymore. It would be better for me not to push anything on the feature/lp branch yet. I will include the new content in the branch and once I've finished and pushed everything, you can make your changes.

**Comment by catcad** [comment]
Ok, great, thanks, then I'll wait for a notification once that is done!

**Comment by bmlancien** [comment]
There is too much content to show at once. To make it more digestable, I'm proposing to do like in the following screenshot: highlight the most important sentences and put the whole text in a dropdown. Like with the other elements on the page, the idea is to present a quick overview about the EC. If a user wants to read more, it's possible, but at least each user should have seen the most important characteristics of en EC.

![Bildschirmfoto vom 2020-11-17 16-33-24](https://user-images.githubusercontent.com/33999424/99410334-a6c42080-28f2-11eb-95bc-16b4c997b10d.png)

**Comment by Bachibouzouk** [comment]
> Exsting PR #83 seems to be adapted for that.
> I just pushed it, see commit [e8bc510](https://github.com/rl-institut/open_plan/commit/e8bc5106d36297ecb1a01cede3aec0c5a42b8837)

meta git workflow comment (just taking the opportunity to raise this point, not accusing you of any wrong doing @TheOneAndra ;)):
Usually you don't push on the branch of someone else whithout talking with them in person (to avoid that the person does not push, make local commits and then realize you had pushed a commit and there might be conflicts). So either talking to each other, or you can always make a new branch from their branch and submit a pull request, that way it does not lead to potential conflicts. 
@mahendrark this example is good for you too :)
