### ISSUE TITLE
The tool + features section is missing

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/open_plan#72]

**Comment by bmlancien** [comment]
@catcad @Bachibouzouk Now I'm thinking there could be a heading for each of the 3 paragraphs because this is a lot of text and I think it would help the visitors to get a quick idea of what these paragraphs are about. Not to repeat the main heading, I was thinking of something like that:

- Heat & electricity
- Open-licence
- Research network

Would you have other suggestions?

![Bildschirmfoto vom 2020-11-16 11-06-04](https://user-images.githubusercontent.com/33999424/99239770-d3e1d780-27fb-11eb-8fad-6d7eb71e2ef7.png)

**Comment by Bachibouzouk** [comment]
I think it is a good idea to have headers for these texts

**Comment by catcad** [comment]
Hi both, 
I also agree.
I would suggest to change 2 of them:

    Heat & electricity --> Sector coupling
    Open-licence
    Research network --> Stakeholder dialogue 
[since it is not just research, also hopefully practical users from private sector]

**Comment by bmlancien** [comment]
Alright, I will include the headings :)
