### ISSUE TITLE
View-component for a map is missing

### ISSUE THREAD

**Issue by mahendrark** [rl-institut/open_plan#91]
This features on two of the interface designs submitted (@TheOneAndra and mine). So it is a 'nice-to-have' feature.

On the 'project setup' view of the progression bar, we can have a small widget that displays the location of a project on a map. (Can be done with Folium or Leaflet) 

If we agree on this, a view-component must be created for this.

**Comment by mahendrark** [comment]
thoughts @Bachibouzouk ?

**Comment by Bachibouzouk** [comment]
Yes, it is nice to have for input of location

**Comment by mahendrark** [comment]
Addressed through PR #82
