### ISSUE TITLE
[Bug] View-comp doesn't appear in the RTD

### ISSUE THREAD

**Issue by TheOneAndra** [rl-institut/open_plan#92]
Describe_the_bug
- Changes made in #82 don't appear in the RTD

**Comment by TheOneAndra** [comment]
**[Update]** Other bugs have been observerd, maybe RDT is just lagging. Check again in 24h.

Last component of the list.

The change appears locally:
![grafik](https://user-images.githubusercontent.com/66671861/99800507-c0ed4100-2b34-11eb-8e32-d1078a2e301f.png)

But not online:
![grafik](https://user-images.githubusercontent.com/66671861/99800406-98fddd80-2b34-11eb-9968-ba5bf0242d5a.png)

**Comment by mahendrark** [comment]
It seems to work now. Lets keep this open and see if the issue persists when we add more view-components.
